### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by DUOLabs333** [Zain-Bin-Arshad/pdf-viewer#1]
I stumbled upon this while searching for a PDF viewer. I want to use it, but I don't understand Arabic. So, could you provide an English translation (Also, a possible bug-- when I clicked on the book icon, no prompt showed up for me to open a file)?

**Comment by Zain-Bin-Arshad** [comment]
Good to hear that you want use this application. I am already working on converting whole application to English. Just to let you know it is not Arabic it is Urdu.

I have implemented completed features too, like:
- Night Mode
- Searching with threading
- Zooming feature
- DocStrings 
- Comments throughout the application and much more.

I was busy with something, so I couldn't clean and push the code. However, I will be pushing the final version on this weekend, I hope you can wait till then. Moreover, thanks for reporting the bug, I think I have already fixed it along with various other bugs.

**Comment by DUOLabs333** [comment]
Ok, thanks. Yeah, it was only until after I read the rest of the REAME did I realize it was Urdu.

**Comment by Zain-Bin-Arshad** [comment]
Hello, I hope you are enjoying best of your health in this pandemic. I have updated the code and added new features, check it out and let me know if you face any problem.
