### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by ghost** [Zain-Bin-Arshad/pdf-viewer#3]
I install all the requirements but it is still not working. 
RuntimeError: Directory 'static/' does not exist

**Comment by Zain-Bin-Arshad** [comment]
Hello @zuozuoxiong please answer following questions:
- What Python version are you using ?
- Are you using a venv ?
- How did you install `fitz` ?
- Which OS are you working on ?

**Comment by VladimirSierra** [comment]
Just create the folder manually in the same location of the .py file

**Comment by Zain-Bin-Arshad** [comment]
@zuozuoxiong I am going to close this issue. Feel free to reach me if you face any problem. Thanks.
