### ISSUE TITLE
Opens up fullscreen and has weird dimensions

### ISSUE THREAD

**Issue by DUOLabs333** [Zain-Bin-Arshad/pdf-viewer#5]
When I open in pdfviewer, it opens up in fullscreen, hiding everything else, and everything is weirdly squashed.

**Comment by Zain-Bin-Arshad** [comment]
@DUOLabs333 can you please attach the image as well?

**Comment by DUOLabs333** [comment]
Here's my screen when I opened it:
![image](https://user-images.githubusercontent.com/49244768/155337865-cd0ee157-d559-41db-bee1-350456041e1e.png)
