### ISSUE TITLE
Opens up fullscreen and has weird dimensions

### ISSUE THREAD

**Issue by ScottCov** [Zain-Bin-Arshad/pdf-viewer#8]
Hi-

Just got to say what a great viewer...well done. I seem to be having the same issue that was brought up a year ago where you cant really see TOC and Notes...That was fixed?

Scott

**Comment by Zain-Bin-Arshad** [comment]
Hey, apologies for the delayed response. I am able to see the TOCs just fine, can you please share the screenshot and PDF file as well. So that I can further test on your specific use case.

Moreover, regarding dimensions, have you fixed them or still an issue?
